<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>TODO: unresolved issues</string>
	<key>foldingStartMarker</key>
	<string>{</string>
	<key>foldingStopMarker</key>
	<string>}</string>
	<key>keyEquivalent</key>
	<string>@^m</string>
	<key>name</key>
	<string>Content Block</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.strongview</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([^\s\.={\[]+)\s*(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.strongview.token</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.strongview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single-line token declaration</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>string.unquoted.strongview</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid-single-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-markup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.strongview</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([^\s\.={\[]+)\s*({\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.strongview.token</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.strongview</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>multi-line token declaration</string>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.strongview</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.strongview</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-markup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.strongview</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subtokens</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>^\s*#[^#].*$</string>
			<key>name</key>
			<string>comment.strongview</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>illegal entries</string>
			<key>match</key>
			<string>^.+$</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.strongview</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml.xsl</string>
				</dict>
			</array>
		</dict>
		<key>invalid-single-line</key>
		<dict>
			<key>match</key>
			<string>,[^=]*$</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<key>subtokens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^|,)\s*(;?)([^\s\.={\[]+)\s*(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.strongview.subtoken</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single-line subtoken declaration</string>
					<key>end</key>
					<string>((?=,)|$)</string>
					<key>name</key>
					<string>string.unquoted.strongview</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-markup</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.strongview</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(;?)([^\s\.={\[]+)\s*({\s*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.strongview.subtoken</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>multi-line subtoken declaration</string>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.strongview</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.strongview</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-markup</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.strongview</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#subtokens</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.strongview_contentblock</string>
	<key>uuid</key>
	<string>2CC6A4F1-17F8-4B2B-93F4-FC0D2E6E07A2</string>
</dict>
</plist>
